const AccountsEvents = {
  CHANGE: "ACCOUNT_EVENTS_CHANGE",
  REQUEST: "ACCOUNT_EVENTS_REQUEST",
  NEW_ACCOUNT: "NEW_ACCOUNT_EVENTS_REQUEST",
  REQUEST_ERROR: "ACCOUNT_EVENTS_REQUEST_ERROR",
};
export default Object.freeze(AccountsEvents);