const SlaveEvents = {
  CHANGE: "AGENTS_EVENTS_CHANGE",
  REQUEST: "AGENTS_EVENTS_REQUEST",
  TOTAL: "AGENTS_EVENTS_TOTAL",
  REQUEST_ERROR: "AGENTS_EVENTS_REQUEST_ERROR",
  REVERT: "AGENTS_EVENTS_REVERT",
  REVERT_ERROR: "AGENTS_EVENTS_REVERT_ERROR",
  FILTER: "AGENTS_FILTER",
};

export default Object.freeze(SlaveEvents);
